### ISSUE TITLE
upgrade: New release '15.10' available.

### ISSUE THREAD

**Issue by serbanghita** [bogdananton/phpunit-selenium-vagrant#3]
Is this an issue?

```
$ vagrant ssh
Welcome to Ubuntu 15.04 (GNU/Linux 3.19.0-33-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Fri Nov 20 20:39:32 UTC 2015

  System load:  0.19              Processes:           95
  Usage of /:   5.6% of 38.80GB   Users logged in:     0
  Memory usage: 6%                IP address for eth0: 10.0.2.15
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

New release '15.10' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Fri Nov 20 20:19:32 2015
```

**Comment by bogdananton** [comment]
Nope.

Run "vagrant box update" to update the base box (static iso).
The instance will not be updated, for this a destroy and up will be needed.

---

From https://docs.vagrantup.com/v2/boxes/versioning.html

`Vagrant can not and does not automatically download the updated box and update the machine because boxes can be relatively large and updating the machine requires destroying it and recreating it, which can cause important data to be lost. Therefore, this process is manual to the extent that the user has to manually enter a command to do it.`

**Comment by serbanghita** [comment]
Does this means that `ubuntu/vivid64` is hardcoded to `Ubuntu 15.04`?
I guess having `config.vm.box_check_update = false` is ok for the moment.
We should include this piece of info in the docs.
